### ISSUE TITLE
Triggers being held is broken.

### ISSUE THREAD

**Issue by likethemammal** [likethemammal/daisywheeljs#19]
The triggers seem to require that the analog be held to work.

**Comment by Triang3l** [comment]
Also you have to pull the triggers to their maximum level. 12% (30/255, to be more precise) should be enough for them to be considered pulled, this is the official dead zone value for the Xbox 360 controller.

**Comment by likethemammal** [comment]
Thanks for the exact value. Knew that I should be accounting for dead zones but didn't wanna dive head first just to figure out the average value.

**Comment by Triang3l** [comment]
Thanks for a quick response to a dead thread revival :)

It seems that the dead zone of the stick is also not being taken into account, the ABCD petal is being randomly selected without me touching the stick (Firefox 46, Windows 10, Xbox 360 controller).

The dead zone radius for the X360 controller (or any other controller in Windows games) is 7849/32767 for the left stick and 8689/32767 for the right. They are listed on MSDN and in the XInput header files: https://msdn.microsoft.com/en-us/library/windows/desktop/ee417001(v=vs.85).aspx

Anyway, great work on making such an awesome input method available on the web!

**Comment by likethemammal** [comment]
Thanks for the detailed breakdown. The browser-os-controller info is a nice touch. Definitely gives me context.

I trust [gamepad-micro](https://github.com/likethemammal/gamepad-micro) to know when things are pressed/held, so the change will mostly be in that lib.

This project can be hard to work on because of the effort of connecting and getting the browser to recognize controllers. It always boosts my motivation when someone appreciates it! Thank you.

**Comment by Triang3l** [comment]
Yes, getting anything to work with the gamepad API is painful :( @w3c should have made it more XInput-/SDL-like.

**Comment by likethemammal** [comment]
So it looks like I have 10% already built https://github.com/likethemammal/daisywheeljs/blob/master/src/js/stores/gamepad.js#L89

I'll set it to 12%, but I'm worried if the 10% wasn't catching most of the noise then 12 probably wouldn't fix your issue completely either.

**Comment by likethemammal** [comment]
@Triang3l Should be fixed now, as of https://github.com/likethemammal/daisywheeljs/commit/7c53d9950e3c4036b5fb6a3e3b96a6ed16832c5a

Reading back, idk where I can up with 12%. Went with assuming anything below 24% (7849/32767) is noise. Appreciate you posting that detailed dead zone article
