### ISSUE TITLE
RT does not work

### ISSUE THREAD

**Issue by L1Q** [likethemammal/daisywheeljs#23]
LT switches letters to numbers, and RT is supposed to switch lowercase to uppercase.
What I see is no reaction to RT whatsoever. Is there a way to check for if RT is registered at all?

**Comment by likethemammal** [comment]
Nah, theres no way atm to see whats registered. The only way the browser knows if a button works is if its been pressed before.

I can't try to reproduce right now cus I'm stuck traveling and in FL (Irma has caused a lot of chaos). It may be the controller you're using. Try [this demo](http://likethemammal.github.io/gamepad-micro/example.html) out and see if RT works there. If it doesnt, that means theres something wrong with the controller or controller setup.

If it works in that demo lmk. That would mean theres an issue with the Daisywheel lib. Maybe from a browser update or something. Either way, thanks for check it out!

**Comment by L1Q** [comment]
It doesn't work on that page D: it works just fine in games though so maybe it's a browser issue.

**Comment by likethemammal** [comment]
Yea, the browser Gamepad API is weird. Sometimes its that the controller isnt supported, sometimes its that the controller doesnt have enough battery, sometimes its that the cable for the controller isnt strong enough to send data just power, sometimes its the usb port itself.

Thats the reason I made `gamepad-micro`, cus its so hard to test support sometimes.

LMK if you figure out the issue and what controller you have, others might have the same issue

**Comment by likethemammal** [comment]
Gonna close since it was a hardware issue
